### PR TITLE
 WFLY-14098 signature test failures in (JAX-RS) JAX-jakarta.ws.rs.core

### PR DESCRIPTION
**Pull request by parsharma**
Issue: https://issues.redhat.com/browse/WFLY-14098?filter=-1

### CODE REVIEW

**Comment by parsharma** [comment]
@scottmarlow As per our discussion, we might need to create a branch and also please let me know if you feel any more changes are required. Thanks

**Comment by scottmarlow** [comment]
@asoldano who should be the first to review this pull request?  

IMO, a new branch should be created for Jakarta EE 9 (e.g. 3.0.x) and some pom.xml changes should be made.

**Comment by asoldano** [comment]
@scottmarlow , we definitely need to keep the JakartaEE 9 dev separate from the EE 8 one, wondering if the latter should move to a branch, though, with the master targetting the latest version.
As for the correctness of the changes, I suggest @ronsigal and possibly @jimma as reviewers.

**Comment by scottmarlow** [comment]
@ronsigal @jimma can you please review these changes and consider whether you want to branch master into a 2.0.x branch (for the existing Jakarta EE 8 2.0.x bug fixing) or something else.  

When you do review the changes in this pull request, keep in mind that this is for Jakarta EE 9 (https://jakarta.ee/specifications/restful-ws/3.0).  It is expected that after a branch is created, someone needs to update the root pom.xml to 3.0.0-SNAPSHOT initially and update the GAV respectively.

**Comment by ronsigal** [comment]
Acknowledging that I'm aware of this pull request.

**Comment by ronsigal** [comment]
src/main/java/module-info.java still refers to javax.ws.rs.

**Comment by ronsigal** [comment]
I guess it doesn't really matter, but wouldn't it be simpler to change the packages in src/test/java as well?

**Comment by ronsigal** [comment]
I moved all of the tests to jakarta.ws.rs and that caused some problems with JaxbLinkTest. So I made a few more changes, upgrading to jakarta.xml.bind, for example. The result is here: https://github.com/ronsigal/jaxrs-api/tree/ee9

**Comment by ronsigal** [comment]
I've made some more changes that I found while comparing version 2.1.6 and version 3.0.0. For example,
* lots of parameters made "final"
* a few code changes, e.g., Link.equals(), EntityTag.equals(), EntityTab.hashCode()
* some things @deprecated

I haven't finished with the comparison, but everything I've done so far is pushed to  https://github.com/ronsigal/jaxrs-api/tree/ee9.

**Comment by scottmarlow** [comment]
> src/main/java/module-info.java still refers to javax.ws.rs.

@ronsigal if you explain what you want @parsharma to change module-info to, she can make further changes.  Or you could make the change yourself after this pull request is completed (any requested changes are made and merged).

**Comment by scottmarlow** [comment]
> I've made some more changes that I found while comparing version 2.1.6 and version 3.0.0. For example,
> 
>     * lots of parameters made "final"
> 
>     * a few code changes, e.g., Link.equals(), EntityTag.equals(), EntityTab.hashCode()
> 
>     * some things @deprecated
> 
> 
> I haven't finished with the comparison, but everything I've done so far is pushed to https://github.com/ronsigal/jaxrs-api/tree/ee9.

I see, thanks @ronsigal for working on the further changes!  IMO, that is a good approach (to just make any further changes needed).  Please do let me know when you are ready for me to build your https://github.com/ronsigal/jaxrs-api/tree/ee9 branch and run some Jakarta EE 9 TCK testing.  

If you send me a private email, I can also explain how you can easily run the EE 9 TCK signature tests (with 4 simple commands that will do all of the work).

**Comment by ronsigal** [comment]
Hi @scottmarlow,

I've been thinking of another approach. One of the things that happened in JAX-RS 3.0 is that a lot of the javadoc was changed just by changing the length of the lines, and it's **really** painful looking for the substantive changes, of which there are a small number. I've been thinking it might make sense to do a reset - that is, copy the files from https://github.com/eclipse-ee4j/jaxrs-api/ and re-apply the Red Hat changes. It would make it much easier in the future to stay in sync. 

-Ron

**Comment by scottmarlow** [comment]
@ronsigal any update on the other approach?

**Comment by ronsigal** [comment]
Hi @scottmarlow,

I finally got back to this issue, and I've created another pull request: https://github.com/jboss/jboss-jakarta-jaxrs-api_spec/pull/7

I have a couple of questions which I'll pose on the other pr.

-Ron

**Pull request closed without merging**
